version: "2.0"

networks:
  custom-network:
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/16
          gateway: 172.11.0.1

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: software
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      custom-network:
        ipv4_address: 172.11.0.2

  currency-converter:
    image: currency-converter:3.0.1
    ports:
      - "8080:8008"
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_URL: ${DB_URL}

      API_KEY: ${FIXER_API_KEY}
      BASE_URL: ${FIXER_API_BASE_URL}

      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_AUTH_SERVER_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
      KEYCLOAK_CREDENTIALS_SECRET: ${KEYCLOAK_CREDENTIALS_SECRET}
    restart: always
    networks:
      custom-network:
        ipv4_address: 172.11.0.3
    depends_on:
      - postgres

  frontend:
    image: currency-converter-angular:3.0.0
    ports:
      - "80:80"
    restart: always
    depends_on:
      - currency-converter
    networks:
      custom-network:
        ipv4_address: 172.11.0.4
